---
title: "Prepare data sets for benchmarking"
author: "Enrico Gaffo"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
    theme: lumen
editor_options: 
  chunk_output_type: console
params:
  outdir: "../benchmark/filtered_simdata/DM1"
  simulated_datasets_qs: "../simulations/semiparametric/simdata/DM1_trimmed_simulated_datasets.qs"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(qs)
library(DT)
library(BiocParallel)
library(batchtools)
library(ggplot2)
```

```{r}
## set the output directory
dir.create(path = params$outdir, recursive = T, showWarnings = F)
datasetList_qs <- file.path(params$outdir, "datasetList.qs")
```

```{r}
nWorkers <- multicoreWorkers() 

## load the simulated data
sim_ds_list <- qread(file = params$simulated_datasets_qs, nthreads = nWorkers)
```

```{r}
## set names to (sub)datasets and remove first level of list
datasetList <- 
  unlist(lapply(names(sim_ds_list), 
                function(x, y) {
                  simData <- y[[x]]$Datasets$sim.data.list
                  names(simData) <- paste(x, sprintf("%02d", 1:length(simData)), sep = "_")
                  simData
                }, 
                y = sim_ds_list), 
         recursive = F)

## fix dataset names
names(datasetList)[grep("mock", names(datasetList), 
                        invert = T)] <- 
  sub("(_[0-9]{2}$)", "_de\\1", 
      names(datasetList)[grep("mock", names(datasetList), 
                              invert = T)])
```

```{r}
## set scheduler parameters for cluster computing
# bpparam <- BatchtoolsParam(workers = length(datasetList), 
#                            saveregistry = F,
#                            cluster = "slurm",
#                            resources = list(ncpus = 1, 
#                                             walltime = 3600, # 1h max
#                                             memory = 4096) # 4Gb, 2048 2 GByte, 8192 8 Gb
# )

## Multithread, single machine
bpparam <- MulticoreParam(nWorkers)
```

# Simulated datsets characteristics

```{r}
# x <- datasetList$N03_bulk_de_01
dataSetStats <- function(x) {
    
    ## total circRNAs
    totCircs <- nrow(x$rowData)
    
    ## non-zero circRNAs
    mat <- x$counts[rowSums(x$counts > 0) > 0, ]
    nonZeroCircs <- nrow(mat) 
    nonZeroFracZeros <- rowSums(mat == 0) / ncol(mat) ## fraction of zeros per circRNAs (only non-zero circRNAs)
    nonZeroMeanBJR <- rowMeans(mat) # apply(mat, 1, median) ## mean BJR per circRNA
    ## zero-counts differential expressed circRNAs
    discardedCircsDeStatus <- 
        x$rowData[!x$rowData %in% rownames(mat),
                  "DE.ind"]
    # table(discardedCircsDeStatus)
    
    
    ## circRNAs expressed in at least 3 samples
    mat <- x$counts[rowSums(x$counts > 0) >= 3, ]
    moreThan3NonZero <- nrow(mat)
    moreThan3NonZeroFracZeros <- rowSums(mat == 0) / ncol(mat)
    moreThan3NonZeroMeanBJR <- rowMeans(mat) # apply(mat, 1, median)
    
    ## circRNAs expressed in at least half the samples
    mat <- x$counts[rowSums(x$counts > 0) >= ceiling( ncol(x$counts) / 2 ), ]
    halfNonZero <- nrow(mat)
    halfNonZeroFracZeros <- rowSums(mat == 0) / ncol(mat)
    halfNonZeroMeanBJR <- rowMeans(mat) # apply(mat, 1, median)
    
    ## return a list
    list(totCircs = totCircs,
         nonZeroCircs = nonZeroCircs,
         moreThan3NonZero = moreThan3NonZero,
         discardedCircsDeStatus = discardedCircsDeStatus, 
         nonZeroFracZeros = nonZeroFracZeros,
         moreThan3NonZeroFracZeros = moreThan3NonZeroFracZeros,
         nonZeroMeanBJR = nonZeroMeanBJR,
         moreThan3NonZeroMeanBJR = moreThan3NonZeroMeanBJR,
         halfNonZero = halfNonZero, 
         halfNonZeroFracZeros = halfNonZeroFracZeros,
         halfNonZeroMeanBJR = halfNonZeroMeanBJR)
}
```

```{r}
# dataSetStatsList <- lapply(datasetList, dataSetStats)
# dataSetStatsList <- bplapply(datasetList, dataSetStats, BPPARAM = bpparam)
dataSetStatsList <- bplapply(datasetList, dataSetStats, 
                             BPPARAM = MulticoreParam(workers = floor(nWorkers / 4)))
```

## Number of circRNAs

```{r}
dataSetStatsDt <- 
    rbindlist(lapply(dataSetStatsList, 
                     function(x) {
                         data.table(totCircs = x$totCircs,
                                    nonZeroCircs = x$nonZeroCircs,
                                    moreThan3NonZero = x$moreThan3NonZero,
                                    halfNonZero = x$halfNonZero)
                     }
    ), 
    idcol = "DS")

dataSetStatsDt[, c("SetSize", "MZP", "Purpose", 
                   "ID") := tstrsplit(DS, "_", type.convert = F),
               by = DS]
```

```{r}
plot_dt <- melt(dataSetStatsDt, 
                id.vars = c("DS", "SetSize", "MZP", "Purpose", "ID"),
                variable.name = "Measure",
                value.name = "nCircs")

ggplot(plot_dt, 
       aes(x = SetSize, y = nCircs, fill = Measure)) +
    geom_boxplot() +
    # scale_y_log10() + ## useless :(
    facet_grid(cols = vars(MZP), 
               rows = vars(Purpose), scales = "free_y") +
    theme_bw()
```

## Fraction of zeros

```{r}
dataSetStatsDt <- 
    rbindlist(lapply(dataSetStatsList, 
                     function(x) {
                         rbindlist(list(`BJR>0 S>=1` = data.table(FracZeros = x$nonZeroFracZeros),
                                        `BJR>0 S>=3` = data.table(FracZeros = x$moreThan3NonZeroFracZeros),
                                        `BJR>0 S>=50%` = data.table(FracZeros = x$halfNonZeroFracZeros)
                                        ), idcol = "Filter", 
                                   )
                     }
    ), 
    idcol = "DS")

dataSetStatsDt[, c("SetSize", "MZP", "Purpose", "ID") := tstrsplit(DS, "_", type.convert = F),
               by = DS]
```

```{r, fig.height=10, fig.width=13}
ggplot(dataSetStatsDt, 
       aes(x = ID, y = FracZeros, color = SetSize)) +
    geom_boxplot(outlier.size = .5) +
    facet_grid(cols = vars(Filter), 
               rows = vars(paste(MZP, Purpose, SetSize)), scales = "free_y") +
    scale_color_discrete(guide = NULL) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1))
```

```{r, fig.height=10, fig.width=13}
ggplot(dataSetStatsDt, 
       aes(x = FracZeros, group = ID, color = SetSize)) +
    geom_density(alpha = .5) +
    facet_grid(rows = vars(paste(Purpose, Filter)), 
               cols = vars(paste(MZP, SetSize)), scales = "free_y") +
    scale_color_discrete(guide = NULL) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1))
```

## Raw expression

```{r}
dataSetStatsDt <- 
    rbindlist(lapply(dataSetStatsList, 
                     function(x) {
                         rbindlist(list(`BJR>0 S>=1` = data.table(MeanBJR = x$nonZeroMeanBJR),
                                        `BJR>0 S>=3` = data.table(MeanBJR = x$moreThan3NonZeroMeanBJR),
                                        `BJR>0 S>=50%` = data.table(MeanBJR = x$halfNonZeroMeanBJR)
                                        ), idcol = "Filter", 
                                   )
                     }
    ), 
    idcol = "DS")

dataSetStatsDt[, c("SetSize", "MZP", "Purpose", "ID") := tstrsplit(DS, "_", type.convert = F),
               by = DS]
```

```{r, fig.height=10, fig.width=13}
ggplot(dataSetStatsDt, 
       aes(x = ID, y = MeanBJR, fill = Filter)) +
    geom_boxplot(outlier.size = .5, position = "dodge") +
    facet_grid(cols = vars(paste(Purpose)), 
               rows = vars(paste(MZP, SetSize)), scales = "free_y") +
    # scale_color_discrete(guide = NULL) +
    scale_y_log10() +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1),
          legend.position = "top")
```

```{r, fig.height=10, fig.width=13}
ggplot(dataSetStatsDt, 
       aes(x = MeanBJR, group = ID, color = SetSize)) +
    geom_density(alpha = .5) +
    facet_grid(cols = vars(paste(SetSize, Purpose)), 
               rows = vars(paste(MZP, Filter)), scales = "free_y") +
    scale_color_discrete(guide = NULL) +
    scale_x_log10() +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1))
```

# Preprocess the data sets

```{r prepare_datasets}
## get the circRNAs kept after filtering in each dataset
circsKept_dt <- 
  rbindlist(lapply(datasetList, 
           function(x) {
             ## remove rows with at least 3 samples expressed
             data.table(x$rowData[rownames(x$counts[rowSums(x$counts > 0) >= 3, ]), ], 
                        keep.rownames = "circ_id")
           }), 
           idcol = "Dataset")

circsKept_dt[, c("SetSize", "MZP", "Purpose", "ID") := tstrsplit(Dataset, "_", 
                                                                 type.convert = F), 
             by = Dataset]
```

```{r}
## prepare datasets
datasetMetaList <-
  lapply(setNames(names(datasetList), nm = names(datasetList)),
         function(dsName, dsList, circList = NULL) {
           
           x <- dsList[[dsName]]
           
           if(!is.null(circList)){
             
             ## get the dataset circrnas
             circsToKeep <- circList[[sub("_[0-9]{2}$", "", dsName)]]$source.ID
             rowdata <- x$rowData[x$rowData$source.ID %in% circsToKeep, ]
             mat <- x$counts[rownames(rowdata), ]
             
           }else{
             
             mat <- x$counts[rowSums(x$counts > 0) >= 3, ]
             rowdata <- x$rowData[rownames(mat), ]
             
           }
           
           coldata <- x$colData[colnames(mat), ]
           discarded.rowData <- x$rowData[!rownames(x$rowData) %in% rownames(mat), ]
           
           list(coldat = data.frame(condition = factor(coldata[, "Group"])),
                cntdat = mat,
                status = as.integer(rowdata[, "DE.ind"]),
                discarded.rowData = discarded.rowData,
                nGenes = nrow(mat))
         }, 
         dsList = datasetList)
```

## Number of circRNAs and DECs simulated

```{r}
ncircs <- sapply(datasetMetaList, function(x) x$nGenes)
totDECs <- sapply(datasetMetaList, function(x) sum(x$status))

datatable(data.frame(NcircRNAs = ncircs, 
                     nDECs = totDECs, 
                     DEC_perc = round(100 * (totDECs / ncircs), 2)), 
          filter = "top")
```

```{r save_datasets}
## save the processed data sets
qsave(x = datasetMetaList,
      file = datasetList_qs,
      nthreads = nWorkers,
      preset = "fast")
```

Processed data sets have been saved in file <a href="`r datasetList_qs`">`r datasetList_qs`</a>.  

# Session info

```{r}
sessionInfo()
```

